### ISSUE TITLE
Joint-control-pkgs bvuiold error (14.04 Indigo Gazebo 4)

### ISSUE THREAD

**Issue by Spottybadrabbit** [JenniferBuehler/joint-control-pkgs#1]
```
 ^
```

/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/src/GazeboJointControl.cpp:124:55: error: expected ‘;’ before ‘_newControllerPtr’
     JointControllerThreadsafe::JointControllerImplPtr _newControllerPtr(new JointControllerThreadsafe::JointControllerImpl(_parent));
                                                       ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/src/GazeboJointControl.cpp:126:66: error: ‘_newControllerPtr’ was not declared in this scope
                           new JointControllerThreadsafe(_parent, _newControllerPtr));
                                                                  ^
make[2]: **\* [joint-control-pkgs/gazebo_joint_control/CMakeFiles/gazebo_joint_control.dir/src/GazeboJointControl.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
In file included from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/GazeboJointControl.h:29:0,
                 from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/GazeboJointControlLocalImpl.h:24,
                 from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/src/GazeboJointControlLocalImpl.cpp:22:
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:70:13: error: ‘JointControllerNewImpl’ does not name a type
     typedef JointControllerNewImpl JointControllerImpl;
             ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:71:13: error: ‘JointControllerNewImplPtr’ does not name a type
     typedef JointControllerNewImplPtr JointControllerImplPtr;
             ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:79:59: error: ‘JointControllerImplPtr’ has not been declared
     explicit JointControllerThreadsafe(ModelPtr& _parent, JointControllerImplPtr& _jointController);
                                                           ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:133:5: error: ‘JointControllerImplPtr’ does not name a type
     JointControllerImplPtr jointController;
     ^
In file included from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/GazeboJointControl.h:29:0,
                 from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/GazeboJointControlLocalImpl.h:24,
                 from /home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/src/GazeboJointControlLocalImplRegistration.cpp:22:
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:70:13: error: ‘JointControllerNewImpl’ does not name a type
     typedef JointControllerNewImpl JointControllerImpl;
             ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:71:13: error: ‘JointControllerNewImplPtr’ does not name a type
     typedef JointControllerNewImplPtr JointControllerImplPtr;
             ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:79:59: error: ‘JointControllerImplPtr’ has not been declared
     explicit JointControllerThreadsafe(ModelPtr& _parent, JointControllerImplPtr& _jointController);
                                                           ^
/home/rover/rover_embedded/catkin_ws/src/joint-control-pkgs/gazebo_joint_control/include/gazebo_joint_control/JointController.h:133:5: error: ‘JointControllerImplPtr’ does not name a type
     JointControllerImplPtr jointController;
     ^
make[2]: **\* [joint-control-pkgs/gazebo_joint_control/CMakeFiles/gazebo_joint_control.dir/src/GazeboJointControlLocalImplRegistration.cpp.o] Error 1
make[2]: **\* [joint-control-pkgs/gazebo_joint_control/CMakeFiles/gazebo_joint_control.dir/src/GazeboJointControlLocalImpl.cpp.o] Error 1
make[1]: **\* [joint-control-pkgs/gazebo_joint_control/CMakeFiles/gazebo_joint_control.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by JenniferBuehler** [comment]
Oh no, sorry! I only saw this now. Github somehow fails to send me email notifications sometimes, even if I'm watching my own repository.

This is a very strange compiler error which I have never seen, can you confirm it is still happening?

**Comment by JenniferBuehler** [comment]
Ah just saw you're using Gazebo 4, that makes sense. 
I haven't tested Gazebo 4 specifically. Try to adjust the version number in
`include/gazebo_joint_control/JointController.h` in the macro `GAZEBO_ADVANCED_JOINTCONTROLLER_VERSION`. Set it to 4, or 3.5, and please let me know which number worked for you.

Sorry once again for the late reply, it's not the first time I'm upset about github not sending me emails.

**Comment by JenniferBuehler** [comment]
Closing for now, please re-open if this issue pops up again.
