### ISSUE TITLE
compilation issue for gazebo

### ISSUE THREAD

**Issue by khoramshahi** [JenniferBuehler/joint-control-pkgs#3]
New in gazebo6: c++11 flags are now required for all downstream software to compile against gazebo. I guess this can be done with the following line:

set(CMAKE_CXX_FLAGS "-std=c++0x ${CMAKE_CXX_FLAGS} ${GAZEBO_CXX_FLAGS}")

in gazebo_joint_control/CMakeLists.txt

**Comment by JenniferBuehler** [comment]
``-std=c++11`` should fix it.  I haven't tried and tested the packages with new versions yet, it's something I would like to do pretty soon, hopefully I'll find some time in the next few weeks.
Meanwhile, I'm happy if you can report any experiences and/or issues you encounter with newer ROS/Gazebo versions!

Cheers
Jennifer

**Comment by khoramshahi** [comment]
Thanks, and I will let you know if I experience new issues.

Best,
Mahdi

**Comment by JenniferBuehler** [comment]
Solved with the last commit.
