### ISSUE TITLE
Compliation error for newer version of Gazebo

### ISSUE THREAD

**Issue by khoramshahi** [JenniferBuehler/joint-control-pkgs#4]
I am getting a error inside this if block:

[#If GAZEBO_MAJOR_VERSION >= GAZEBO_ADVANCED_JOINTCONTROLLER_VERSION
](https://github.com/JenniferBuehler/joint-control-pkgs/blob/master/gazebo_joint_control/src/GazeboJointControl.cpp#L163)

because ‘_modelJointController’ was not declared in this scope.

I just added the its definition like this, and it is ok now:
    physics::JointControllerPtr _modelJointController = _parent->GetJointController();

**Comment by JenniferBuehler** [comment]
Ok, thanks for letting me know! As with issue #3 , I am hoping to get the stuff up and running with newer versions soon.

**Comment by khoramshahi** [comment]
You're welcome!

Cheers!

**Comment by JenniferBuehler** [comment]
Solved with the last commit. Sorry this was a bug introduced when I was debugging on an older version and I didn't notice it.
