### ISSUE TITLE
error in (fmax)

### ISSUE THREAD

**Issue by hsilva7** [JenniferBuehler/joint-control-pkgs#8]
In my robot arm simulation, with ROS melodic with Gazebo 9.0, I found that one of the joints wasn't holding position, always being pulled down, only happened to this one joint. 
I changed the PID values, velocity values and max force values but the joint was still not behaving as it should.

I also noticed an error when launching my robot in Gazebo

>[Err] [ODEJoint.cc:504] SetParam(fmax) boost any_cast error:boost::bad_any_cast: failed conversion using boost::any_cast

Looking at the Gazebo's [Setting Velocity on Joints and Links ](http://gazebosim.org/tutorials?tut=set_velocity&cat=) states:

> Note The value parameter must have exactly the right type. Joint motors require setting double parameters. This call will work joint->SetParam('fmax', 0, 0.0) while this will have a runtime error joint->SetParam('fmax', 0, 0).

Looking at the plugin in gazebo_joint_control/src/GazeboJointControl.cpp

https://github.com/JenniferBuehler/joint-control-pkgs/blob/6db7d2447054622712690669036a256432fd7ba2/gazebo_joint_control/src/GazeboJointControl.cpp#L202

`max_force` is defined as float

my solution was to cast to double in line 222

https://github.com/JenniferBuehler/joint-control-pkgs/blob/6db7d2447054622712690669036a256432fd7ba2/gazebo_joint_control/src/GazeboJointControl.cpp#L222

`joint->SetParam("fmax", 0, (double) max_force);`

I am not sure if this is an error or if it is only for my robot configuration

**Comment by JenniferBuehler** [comment]
Hi, thanks for reporting this! 
So if you cast to double, does the error message go away, and do things then work as expected?

Are you using a velocity, position or effort PID controller?

**Comment by hsilva7** [comment]
As far as I have tested both position and velocity work as expected (didn't test for effort controller), and there is no error message.


On another note: changing the PID values with position and velocity control seems to have little, or none, effect in the motion(?)

**Comment by JenniferBuehler** [comment]
After a literal ETERNITY, I finally got around to do this. The fix works, and has been merged. Thanks for reporting :)
